import { createRoot } from 'react-dom/client'
// import '../../styles/rotatingGalleryStyles.css'
import { Logo } from '@pmndrs/branding'
import { App } from './rotatingGallery'
import Navbar from '../Navbar';

import {
  Box,
  Center,
  Text,
  Heading,
  VStack,
  Button,
  Container,
  HStack,
  Image as ChakraImage,
  Link
} from '@chakra-ui/react';

/*
Model JSX auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 model.glb --transform --simplify --resolution=2048
Author: Omar Faruq Tawsif (https://sketchfab.com/omarfaruqtawsif32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
*/

export function Root() {
  return (
    <Box minH='80vh' bg='#37C6FF'>

<Navbar bg={{base: 'transparent', lg: 'none'}} />

      <Center h={{base: '65vh', md: "80vh"}}>
        <VStack spacing={8}>
          <Heading
                    lineHeight={1.1}
                    fontWeight={600}
                    fontFamily='Space Mono'
                    color='white'
                    fontSize={{ base: 'xl', sm: '4xl', lg: '4xl' }}>
              Loading Possible Futures ...
            </Heading>
          <App />
        </VStack>
      </Center>
      <div style={{ position: 'absolute', pointerEvents: 'none', top: 0, left: 0, width: '100vw', height: '100vh' }}>
        {/* <a href="https://pmnd.rs/" style={{ position: 'absolute', bottom: 40, left: 90, fontSize: '13px' }}>
          PRAXIS Labs
          <br />
        </a>
        <Logo style={{ position: 'absolute', bottom: 40, left: 40, width: 30 }} /> */}

      <Box position="absolute" bottom={{base:"20", md: "0"}} right={{base:"0", md: "0"}} p={{base: 0, md: 20}}>

      <HStack spacing={8}>
      <ChakraImage
                  mt={2}
                  mr={8}

                      src={'https://res.cloudinary.com/medoptics-image-cloud/image/upload/v1747920205/praxis-labs-logo_olljaf.png'}
                      alt="Doen Logo"
                      height={{base: '40px', md: '40px'}} // Adjust height as needed
                      width={'auto'} // Maintain aspect ratio
                      // ml={'64px'}
                  />
        <ChakraImage
                  mt={2}
                  mr={8}
                      src={'https://res.cloudinary.com/medoptics-image-cloud/image/upload/v1747919860/BritishCouncil_baddf4.png'}
                      alt="British Council Logo"
                      height={{base: '40px', md: '40px'}} // Adjust height as needed
                      width={'auto'} // Maintain aspect ratio
                      // ml={'64px'}
                  />
      <ChakraImage
                  mt={2}
                  mr={8}

                      src={'https://res.cloudinary.com/medoptics-image-cloud/image/upload/v1747919874/Doen-Logo_nn8ua7.png'}
                      alt="Doen Logo"
                      height={{base: '40px', md: '40px'}} // Adjust height as needed
                      width={'auto'} // Maintain aspect ratio
                      // ml={'64px'}
                  />

      </HStack>
      </Box>

        <a style={{ position: 'absolute', top: 40, right: 40, fontSize: '13px' }} href="#">
          scroll up/down ...
        </a>
      </div>{' '}
    </Box>
  )
}

