import { App } from './rotatingGallery'
import Navbar from '../Navbar';

import {
  Box,
  Center,
  Text,
  Heading,
  VStack,
  Button,
  Container,
  HStack,
  Image as ChakraImage,
  Link as ChakraLink // Alias Chakra UI's Link to avoid naming conflict
} from '@chakra-ui/react';
import NextLink from 'next/link'; // Import Next.js Link

/*
Model JSX auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 model.glb --transform --simplify --resolution=2048
Author: Omar Faruq Tawsif (https://sketchfab.com/omarfaruqtawsif32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
*/

export function Root() {
  
  return (
    <Box minH='100vh' bg='#37C6FF'>

<Navbar bg={{base: 'transparent', lg: 'none'}} />

      <Center h={{base: '65vh', md: "80vh"}}>
        <VStack spacing={8}>
          {/* <Heading
                    lineHeight={1.1}
                    fontWeight={600}
                    fontFamily='Space Mono'
                    color='white'
                    fontSize={{ base: 'xl', sm: '4xl', lg: '4xl' }}>
              Loading Possible Futures ...
            </Heading> */}
          <App />
        </VStack>
      </Center>
      <div style={{ position: 'absolute', pointerEvents: 'none', top: 0, left: 0, width: '100vw', height: '100vh' }}>
        {/* <a href="https://pmnd.rs/" style={{ position: 'absolute', bottom: 40, left: 90, fontSize: '13px' }}>
          PRAXIS Labs
          <br />
        </a>
        <Logo style={{ position: 'absolute', bottom: 40, left: 40, width: 30 }} /> */}

      <Box position="absolute" bottom={{base:"20", md: "0"}} left={{base:"0", md: "0"}} p={{base: 0, md: 20}} ml={{base: 8}} style={{ pointerEvents: 'auto' }}>

      <Box mt={2}>
        <NextLink href="/info" passHref> {/* Use NextLink */}
             <Text
             color={{base:" #FFFFFF", md: '#FFFFFF'}}
             fontFamily={"Space Mono"}
             fontSize={{base:'10px', md: '1rem'}}
             textAlign='right'
             fontWeight={600}
             textDecoration='underline'
             _hover={{ textDecoration: 'none' }} // Apply hover style directly to Text
             >
             More Info
             </Text>
        </NextLink>
        </Box>

        <Box mt={2}>
        <NextLink href="https://www.afropocene.com/" passHref>
             <Text
             color={{base:" #FFFFFF", md: '#FFFFFF'}}
             fontFamily={"Space Mono"}
             fontSize={{base:'10px', md: '1rem'}}
             textAlign='right'
             fontWeight={600}
             textDecoration='underline'
             _hover={{ textDecoration: 'none' }} // Apply hover style directly to Text

             >
             Back to Main Site
             </Text>
        </NextLink>
        </Box>

        <Box mt={2}>
        <NextLink href="https://store.pesapal.com/afropocene" passHref> {/* Use NextLink */}
             <Text
             color={{base:" #FFFFFF", md: '#FFFFFF'}}
             fontFamily={"Space Mono"}
             fontSize={{base:'10px', md: '1rem'}}
             textAlign='right'
             fontWeight={600}
             textDecoration='underline'
             _hover={{ textDecoration: 'none' }} // Apply hover style directly to Text
             >
             Donate
             </Text>
        </NextLink>
        </Box>
      </Box>

      <Box position="absolute" bottom={{base:"20", md: "0"}} right={{base:"0", md: "0"}} p={{base: 0, md: 20}}>
        <HStack spacing={8}>

        <ChakraImage
                      mt={2}
                      mr={8}

                          src={'https://res.cloudinary.com/medoptics-image-cloud/image/upload/v1752656800/africanArtsTrust_e3pybb.jpg'}
                          alt="Doen Logo"
                          height={{base: '30px', md: '40px'}} // Adjust height as needed
                          width={'auto'} // Maintain aspect ratio
                          // ml={'64px'}
                      />
          {/* <ChakraImage
                      mt={2}
                      mr={8}

                          src={'https://res.cloudinary.com/medoptics-image-cloud/image/upload/v1747920205/praxis-labs-logo_olljaf.png'}
                          alt="Doen Logo"
                          height={{base: '30px', md: '40px'}} // Adjust height as needed
                          width={'auto'} // Maintain aspect ratio
                          // ml={'64px'}
                      /> */}
            {/* <ChakraImage
                      mt={2}
                      mr={8}
                          src={'https://res.cloudinary.com/medoptics-image-cloud/image/upload/v1747919860/BritishCouncil_baddf4.png'}
                          alt="British Council Logo"
                          height={{base: '20px', md: '40px'}} // Adjust height as needed
                          width={'auto'} // Maintain aspect ratio
                          // ml={'64px'}
                      /> */}
          <ChakraImage
                      mt={2}
                      mr={8}

                          src={'https://res.cloudinary.com/medoptics-image-cloud/image/upload/v1747919874/Doen-Logo_nn8ua7.png'}
                          alt="Doen Logo"
                          height={{base: '30px', md: '40px'}} // Adjust height as needed
                          width={'auto'} // Maintain aspect ratio
                          // ml={'64px'}
                      />

        </HStack>
      </Box>
      <Box 
      display={{base: 'flex', lg: 'none'}}
      style={{ position: 'absolute', top: 30, right: 40 }}
      maxW='120px'
      >


      <VStack >

        <Text fontFamily='Space Mono'
          color='white'

        fontSize='10px' textAlign='right'>
        Scroll Above Carousel
        </Text>
        <Box ml='7'>
        <Text fontFamily='Space Mono'
          color='white'

        fontSize='10px' textAlign='right' ml={2} >
          Click to Open
        </Text>
        </Box>
        </VStack>
      </Box>

      <Box 
      display={{base: 'none', lg: 'flex'}}
      style={{ position: 'absolute', top: 40, right: 40 }}
      maxW='200px'
      >
        <VStack>
        {/* <Box mt={2}>
        <NextLink href="https://www.afropocene.com/" passHref>
             <ChakraLink>

             <Text
             color=" #ffffff"
             fontFamily={"Space Mono"}
             fontSize ={"1rem"}
             fontWeight={500}
             >
             Back to main site
             </Text>

             </ChakraLink>
        </NextLink>
        </Box> */}

        <Text fontFamily='Space Mono'
          color='white'
          fontSize='14px'>
          Scroll to Move Carousel
          </Text>
        <Text fontFamily='Space Mono'
         color='white'
         fontSize='14px' >
          Click on Image to Open
        </Text>
        </VStack>
      </Box>

        {/* <a style={{ position: 'absolute', top: 40, right: 40, fontSize: '13px' }} href="#">
          Scroll to move carousel
        </a> */}
        {/* <a style={{ position: 'absolute', top: 40, right: 40, fontSize: '13px' }} href="#">
          click to open
        </a> */}
      </div>{' '}
    </Box>
  )
}

